# ===== MARKET CONFIG =====
TIMEZONE = "Asia/Kolkata"
REFRESH_MINUTES = 10

# ===== INDICES =====
#INDEX_SYMBOLS = ["NIFTY", "BANKNIFTY"]

# ===== F&O STOCKS (NSE official list – expandable) =====
FNO_SYMBOLS = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","NIFTY", "BANKNIFTY",
    "INFY","SBIN","HCLTECH","KOTAKBANK","LT","ITC","HINDUNILVR","AXISBANK",
    "MARUTI","TECHM","ASIANPAINT","WIPRO","BAJAJ-AUTO","BHARTIARTL","DRREDDY",
    "TITAN","ULTRACEMCO","HDFCLIFE","DIVISLAB","ADANIPORTS","INDUSINDBK","JSWSTEEL",
    "ONGC","GRASIM","COALINDIA","BPCL","SHREECEM","HDFCBANK","LTIM","SUNPHARMA",
    "EICHERMOT","TATAMOTORS","HCLTECH","UPL","ICICIPRULI","BAJFINANCE","CIPLA",
    "BRITANNIA","POWERGRID","NTPC","TATACONSUM","VEDL","SBILIFE","TECHM","GAIL",
    "RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","AXISBANK","KOTAKBANK","LT",
    "ITC","HINDUNILVR","SBIN","HCLTECH","MARUTI","BAJAJFINSV","ADANIENT","ADANIGREEN",
    "BAJAJ-AUTO","BHARTIARTL","DRREDDY","TITAN","ULTRACEMCO","DIVISLAB","ASIANPAINT",
    "ONGC","GRASIM","COALINDIA","BPCL","SHREECEM","LTIM","SUNPHARMA","EICHERMOT",
    "TATAMOTORS","UPL","ICICIPRULI","BAJFINANCE","CIPLA","BRITANNIA","POWERGRID",
    "NTPC","TATACONSUM","VEDL","SBILIFE","GAIL","RELIANCE","TCS","INFY","HDFCBANK",
    "ICICIBANK","AXISBANK","KOTAKBANK","LT","ITC","HINDUNILVR","SBIN","HCLTECH",
    "MARUTI","TECHM","ASIANPAINT","WIPRO","BAJAJ-AUTO","BHARTIARTL","DRREDDY",
    "TITAN","ULTRACEMCO","HDFCLIFE","DIVISLAB","ADANIPORTS","INDUSINDBK","JSWSTEEL",
    "ONGC","GRASIM","COALINDIA","BPCL","SHREECEM","HDFCBANK","LTIM","SUNPHARMA",
    "EICHERMOT","TATAMOTORS","HCLTECH","UPL","ICICIPRULI","BAJFINANCE","CIPLA",
    "BRITANNIA","POWERGRID","NTPC","TATACONSUM","VEDL","SBILIFE","TECHM","GAIL"
]

# ===== EMAIL CONFIG =====
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
EMAIL_FROM = "yourmail@gmail.com"
EMAIL_PASSWORD = "your_app_password"
EMAIL_TO = ["yourmail@gmail.com"]

# ===== ALERT CONTROL =====
MIN_CONFIDENCE = 60   # %
