# ================== ZERODHA CONFIG ==================
ZERODHA_API_KEY = "z9rful06a9890v8m"
ZERODHA_API_SECRET = "z96wwv8htnih8n792673jj5trqc4hutm"
ZERODHA_REDIRECT_URI = "http://127.0.0.1:5010"
ZERODHA_ACCESS_TOKEN = "1Ga0wgJD3kdHtD6eTCQCVaqNL2z7QEor"

## ================== MARKET CONFIG ==================
REFRESH_MINUTES = 5
TIMEZONE = "Asia/Kolkata"

# ================== SYMBOLS ==================
# F&O / scanner symbols
FNO_SYMBOLS = [
    "BANKNIFTY","FINNIFTY","MIDCPNIFTY","NIFTY","NIFTYNXT50","360ONE",
    "ABB","ABCAPITAL","ADANIENSOL","ADANIENT","ADANIGREEN","ADANIPORTS",
    "ALKEM","AMBER","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP",
    "ASHOKLEY","ASIANPAINT","ASTRAL","AUBANK","AUROPHARMA","AXISBANK",
    "BAJAJ-AUTO","BAJAJFINSV","BAJAJHLDNG","BAJFINANCE","BANDHANBNK",
    "BANKBARODA","BANKINDIA","BDL","BEL","BHARATFORG","BHARTIARTL",
    "BHEL","BIOCON","BLUESTARCO","BOSCHLTD","BPCL","BRITANNIA","BSE",
    "CAMS","CANBK","CDSL","CGPOWER","CHOLAFIN","CIPLA","COALINDIA",
    "COFORGE","COLPAL","CONCOR","CROMPTON","CUMMINSIND","DABUR",
    "DALBHARAT","DELHIVERY","DIVISLAB","DIXON","DLF","DMART","DRREDDY",
    "EICHERMOT","ETERNAL","EXIDEIND","FEDERALBNK","FORTIS","GAIL",
    "GLENMARK","GMRAIRPORT","GODREJCP","GODREJPROP","GRASIM","HAL",
    "HAVELLS","HCLTECH","HDFCAMC","HDFCBANK","HDFCLIFE","HEROMOTOCO",
    "HINDALCO","HINDPETRO","HINDUNILVR","HINDZINC","HUDCO","ICICIBANK",
    "ICICIGI","ICICIPRULI","IDEA","IDFCFIRSTB","IEX","INDHOTEL",
    "INDIANB","INDIGO","INDUSINDBK","INDUSTOWER","INFY","INOXWIND",
    "IOC","IRCTC","IREDA","IRFC","ITC","JINDALSTEL","JIOFIN","JSWENERGY",
    "JSWSTEEL","JUBLFOOD","KALYANKJIL","KAYNES","KEI","KFINTECH",
    "KOTAKBANK","KPITTECH","LAURUSLABS","LICHSGFIN","LICI","LODHA","LT",
    "LTF","LTIM","LUPIN","M&M","MANAPPURAM","MANKIND","MARICO","MARUTI",
    "MAXHEALTH","MAZDOCK","MCX","MFSL","MOTHERSON","MPHASIS","MUTHOOTFIN",
    "NATIONALUM","NAUKRI","NBCC","NESTLEIND","NHPC","NMDC","NTPC","NUVAMA",
    "NYKAA","OBEROIRLTY","OFSS","OIL","ONGC","PAGEIND","PATANJALI","PAYTM",
    "PERSISTENT","PETRONET","PFC","PGEL","PHOENIXLTD","PIDILITIND","PIIND",
    "PNB","PNBHOUSING","POLICYBZR","POLYCAB","POWERGRID","POWERINDIA",
    "PPLPHARMA","PREMIERENE","PRESTIGE","RBLBANK","RECLTD","RELIANCE",
    "RVNL","SAIL","SAMMAANCAP","SBICARD","SBILIFE","SBIN","SHREECEM",
    "SHRIRAMFIN","SIEMENS","SOLARINDS","SONACOMS","SRF","SUNPHARMA",
    "SUPREMEIND","SUZLON","SWIGGY","SYNGENE","TATACONSUM","TATAELXSI",
    "TATAPOWER","TATASTEEL","TATATECH","TCS","TECHM","TIINDIA","TITAN",
    "TMPV","TORNTPHARM","TORNTPOWER","TRENT","TVSMOTOR","ULTRACEMCO",
    "UNIONBANK","UNITDSPR","UNOMINDA","UPL","VBL","VEDL","VOLTAS",
    "WAAREEENER","WIPRO","YESBANK","ZYDUSLIFE"
]

# ================== Email Config ==================
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
EMAIL_FROM = "sambhajimene@gmail.com"
EMAIL_PASSWORD = "jgebigpsoeqqwrfa"
EMAIL_TO = ["sambhajimene@gmail.com"]

### ================== Alerts Config ===========Sambhaji Mene=======
MIN_CONFIDENCE = 30  # %
